query rooms {
    rooms {
        id
        name
        disabled
        description
        own_messages {
            __typename
        }
    }
}

query messages($roomId: String!) {
    messages(roomId: $roomId) {
        id
        text
        roomId
        userID
        isSender
    }
}

