// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	ID     string `json:"id"`
	RoomID string `json:"roomId"`
	Text   string `json:"text"`
}

type Room struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	Disabled    bool       `json:"disabled"`
	OwnMessages []*Message `json:"own_messages"`
}
