// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateMessageInput struct {
	RoomID string `json:"roomId"`
	UserID string `json:"userId"`
	Text   string `json:"text"`
}

type Message struct {
	ID       string `json:"id"`
	RoomID   string `json:"roomId"`
	Text     string `json:"text"`
	UserID   string `json:"userId"`
	IsSender bool   `json:"isSender"`
}

type Room struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	Disabled    bool       `json:"disabled"`
	OwnMessages []*Message `json:"own_messages"`
}
